### ISSUE TITLE
Einrichtung/Konfiguration

### ISSUE THREAD

**Issue by Matzeee** [zuloo/snyp#1]
Zunächst vielen Dank für die Mühe so ein Projekt zu starten.
Habe mich sehr gefreut, dass sich nun doch noch etwas tut mit dem guten esniper.

Ich hoffe es ist in Ordnung wenn ich auf Deutsch schreibe?

esniper läuft bei mir bereits erfolgreich auf einem RaspberryPi in Verbindung mit dem esniper-frontend, welches auch hier auf git von syssi aktualisiert wurde.

Ich bekomme nun leider snyp nicht richtig zum laufen und würde mich sehr über Hilfe freuen.
Habe NGINX, php, mysql und phpmyadmin installiert und sonst die Anleitung befolgt.
Die Pfade von sh und php passen, esniper ist im Standartverzeichnis.

setperms.sh habe ich in /var/www/snyp kopiert und ausgeführt. Zusätzlich ein
chown -R www-data:www-data /var/www

Ich war mir bei der Collation unsicher und habe utf8_general_ci genommen (beim Hochladen der esniper.sql charset utf-8).

Leider bekomme ich darauf nur folgende Ausgabe:

![snyp](https://f.cloud.github.com/assets/6171490/2306255/337ba30a-a280-11e3-950c-efe7ceb0cb23.PNG)

Wenn ich in der config.inc absichtlich ein falsches Sqlpasswort oder DB_Name eintrage bekomme ich auch direkt einen Fehler.

Habe selbst den Ordner /var/www/snyp/tmp angelegt. Wird die esniper.cfg automatisch erstellt? Welcher Ordner bietet sich dafür an? Oder einfach /var/www/snyp/esniper.cfg lassen?

**Comment by zuloo** [comment]
Hi,

meine Verzeichnisstruktur sieht so aus:

var/www/snyp/
    |
    +-htdoc/
    |   |
    |   +-js/
    |   |
    |   +-css/
    |   |
    |   +-images/
    |   |
    |   +-All the php files and stuff
    |
    +-tmp/
    |
    +-log/
    |
    +-esniper.cfg

wobei htdoc das Webroot ist.

Es sieht so aus, als ob er die CSS-Dateien nicht findet, dann wahrscheinlich auch nicht die  Javascript-Dateien.
Steht was in den Nginx-Logs? ich verwende Apache, und bin nicht sicher ob es in nginx einfach 1zu1 funktioniert.

Im moment funktioniert aber die Beobachtungsliste nicht richtig, weil eBay da seit neuestem auf Ajax und JS setzt.
Ich muss mal sehen ob ich die Ajax-Requests aufschlüsseln kann, die dann die eigentliche Liste laden… wenn das nicht
geht würde ich vllt. versuchen das ganze noch in Python zu machen, da lässt sich JS evaluieren.

Viele Grüße

## Jan B. FIedler

Jan B. Fiedler IT-Solutions

Hohlstraße 8
65606 Villmar-Weyer

Tel.: 06483 24 90 35
Mail: jbf@zuloo.de
Web:  www.zuloo.de

Bank: KSK Weilburg
IBAN: DE59 5115 1919 0057 4619 80
SBIC: HELADEF1WEI

USt-ID: DE223645423

Am 03.03.2014 um 04:54 schrieb Matzeee notifications@github.com:

**Comment by Matzeee** [comment]
Vielen Dank, es war wohl ein Rechteproblem. Ich habe das Repo neu geklont und die setperms.sh weggelassen und es funktioniert.

Bei mir ist einfach /var/www das Webroot. Die Ordnerhierachie habe ich unverändert gelassen und in /var/www/snyp geklont.
Hatte dann die setperm.sh in /var/www/snyp kopiert und ausgeführt.
Durch chmod 0644 \* wurde wohl den ccs und js Ordnern das X entzogen und sie konnten gar nicht mehr gelesen werden.

Nun kann ich auch Gruppen erstellen. Wenn ich einen Snipe setzen will bekomme ich jedoch einen SQL-Fehler:

SQL/DB Error -- [You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1]

Ich weiß, ist wenig aussagekräftig aber ich weiß auch nicht wo ich suchen soll. Die Gruppen werden wie gesagt korrekt erstellt und erscheinen auch in phpmyadmin.

Und noch eine ganz andere Frage: Ist es ohne größeren Aufwand möglich z.B. SQLite zu verwenden? MySQL frisst auf dem Pi über 9% Ram. Zusammen mit einem Mediacenter wird das knapp. Wenn nicht muss eben ein 2. Pi oder ähnliches her…

Wegen der Beobachtungsliste: Kann man stattdessen Lesezeichen wie bei es-f nutzen um schneller Auktionen hinzuzufügen?

**Comment by Matzeee** [comment]
Ok, der Fehler tritt bei mir nur dann auf, wenn eine ganze URL hinzugefügt wird. Mit einer einzelnen Auktion klappt es.

Ich habe nur meine Zweifel, dass bei den Gruppen tatsächlich nur ein Artikel ersteigert wird.
Es wird bei mir unabhängig von der Gruppeneinstellung für jeden Artikel ein esniper-Prozess mit genau einer Auktion gestartet.
Müssten denn nicht alle Auktionen einer Gruppe in einer .ebaysnipe Datei in tmp zusammengefasst werden? D.h. beim Hinzufügen einer Auktion zu einer laufenden Gruppe müsste der Artikel in dieselbe "auction file" geschrieben werden (evtl quantity = 1 setzen) und wahrscheinlich der esniper-Prozess neu gestartet werden?

Und noch zwei kleine Schönheitsfehler:
Im Webinterface wird alles als "beendet" angezeigt. Im popup wenn über einen Artikel gefahren wird steht es aber korrekt.
Wenn eine Auktion hinzugefügt wird, wird der korrekte Titel erst nach einem erneuten reload angezeigt.

Ich würde wirklich gerne selber bei der Weiterentwicklung mithelfen. Leider ist bei mir bis auf ein Schuljahr mit Delphi alles learning by doing…
Hoffe, dass zumindest das Testen hilft (war auch bereits mein Nebejob).

Oder ist ein kurzer telefonischer Kontakt erwünscht? Vielleicht kann ich doch etwas beitragen, wenn ich den grundsätzlichen Aufbau besser verstehe. Syntax kann ich mir vielleicht auch selbst aneignen und es werden wahrscheinlich keine hochkomplexen Algorithmen gebraucht?
